#!/bin/sh

namespace="$1"
shift
project_name="$1"
shift

for image in "$@"; do
  echo "Docker build Dockerfile-${image} and tag with ${namespace}/${project_name}-${image}:latest"
  docker build -f Dockerfile-${image} --build-arg BUNDLE_GEM__FURY__IO=${FURY_AUTH} -t ${namespace}/${project_name}-${image}:latest .
done

