#!/bin/sh

registry_id="$1"
shift
git_commit="$1"
shift

. run-or-die

for image_name in "$@"; do
  run-or-die "docker tag ${image_name}:latest ${registry_id}.dkr.ecr.us-east-1.amazonaws.com/${image_name}:${git_commit}"
  run-or-die "docker push ${registry_id}.dkr.ecr.us-east-1.amazonaws.com/${image_name}:${git_commit}"

  if [ $CODEBUILD_MASTER_DEPLOY ]; then
    run-or-die "docker tag ${image_name}:latest ${registry_id}.dkr.ecr.us-east-1.amazonaws.com/${image_name}:latest"
    run-or-die "docker push ${registry_id}.dkr.ecr.us-east-1.amazonaws.com/${image_name}:latest"
  fi
done
