#!/bin/sh

extra_args="$@"

. ./run-or-die

if [ $CODEBUILD_MASTER_DEPLOY ]; then
  echo "Maven clean deploy"
  run_or_die "mvn -U clean deploy -Dgit_commit=${git_commit} ${extra_args}"
else
  echo "Maven clean verify"
  run_or_die "mvn -U clean verify -Dgit_commit=${git_commit} ${extra_args}"
fi
