#!/bin/sh

image_name="$1"

. ./run-or-die

if [ $CODEBUILD_MASTER_DEPLOY ]; then
  echo "Maven clean deploy"
  run_or_die "mvn -U clean deploy -Dgit_commit=${git_commit} -Dimage_name=${image_name}"
else
  echo "Maven clean verify"
  run_or_die "mvn -U clean verify -Dgit_commit=${git_commit} -Dimage_name=${image_name}"
fi
